// const descriptions = [
//   { id: "clear sky", description: "description_clear_sky", summary: "clear_sky" },
//   { id: "few clouds", description: "description_few_clouds", summary: "few_clouds" },
//   { id: "scattered clouds", description: "description_scattered_clouds", summary: "scattered_clouds" },
//   { id: "broken clouds", description: "description_broken_clouds", summary: "broken_clouds" },
//   { id: "overcast clouds", description: "description_overcast_clouds", summary: "overcast_clouds" },
//   { id: "shower rain", description: "description_shower_rain", summary: "shower_rain" },
//   { id: "rain", description: "description_rain", summary: "rain" },
//   { id: "thunderstorm", description: "description_thunderstorm", summary: "thunderstorm" },
//   { id: "snow", description: "description_snow", summary: "snow" },
//   { id: "mist", description: "description_mist", summary: "mist" },
//   { id: "fog", description: "description_fog", summary: "fog" },
//   { id: "drizzle", description: "description_drizzle", summary: "drizzle" },
//   { id: "light rain", description: "description_light_rain", summary: "light_rain" },
//   { id: "moderate rain", description: "description_moderate_rain", summary: "moderate_rain" },
//   { id: "heavy intensity rain", description: "description_heavy_intensity_rain", summary: "heavy_intensity_rain" },
//   { id: "very heavy rain", description: "description_very_heavy_rain", summary: "very_heavy_rain" },
//   { id: "extreme rain", description: "description_extreme_rain", summary: "extreme_rain" },
//   { id: "freezing rain", description: "description_freezing_rain", summary: "freezing_rain" },
//   { id: "light intensity shower rain", description: "description_light_intensity_shower_rain", summary: "light_intensity_shower_rain" },
//   { id: "heavy intensity shower rain", description: "description_heavy_intensity_shower_rain", summary: "heavy_intensity_shower_rain" },
//   { id: "light snow", description: "description_light_snow", summary: "light_snow" },
//   { id: "heavy snow", description: "description_heavy_snow", summary: "heavy_snow" },
//   { id: "sleet", description: "description_sleet", summary: "sleet" },
//   { id: "light shower sleet", description: "description_light_shower_sleet", summary: "light_shower_sleet" },
//   { id: "shower sleet", description: "description_shower_sleet", summary: "shower_sleet" },
//   { id: "light rain and snow", description: "description_light_rain_and_snow", summary: "light_rain_and_snow" },
//   { id: "rain and snow", description: "description_rain_and_snow", summary: "rain_and_snow" },
//   { id: "light shower snow", description: "description_light_shower_snow", summary: "light_shower_snow" },
//   { id: "shower snow", description: "description_shower_snow", summary: "shower_snow" },
//   { id: "heavy shower snow", description: "description_heavy_shower_snow", summary: "heavy_shower_snow" },
//   { id: "haze", description: "description_haze", summary: "haze" },
//   { id: "smoke", description: "description_smoke", summary: "smoke" },
//   { id: "dust", description: "description_dust", summary: "dust" },
//   { id: "sand", description: "description_sand", summary: "sand" },
//   { id: "volcanic ash", description: "description_volcanic_ash", summary: "volcanic_ash" },
//   { id: "squalls", description: "description_squalls", summary: "squalls" },
//   { id: "tornado", description: "description_tornado", summary: "tornado" },
// ];

// export const findDescriptionById = (id: string) => {
//   const match = descriptions.find((item) => item.id === id);
//   if (match) return match;
//   return { id: id, description: "unknown", summary: "unknown" };
// };

const idToKey: Record<string, string> = {
  "clear sky": "clear_sky",
  "few clouds": "few_clouds",
  "scattered clouds": "scattered_clouds",
  "broken clouds": "broken_clouds",
  "overcast clouds": "overcast_clouds",
  "shower rain": "shower_rain",
  rain: "rain",
  thunderstorm: "thunderstorm",
  snow: "snow",
  mist: "mist",
  fog: "fog",
  drizzle: "drizzle",
  "light rain": "light_rain",
  "moderate rain": "moderate_rain",
  "heavy intensity rain": "heavy_intensity_rain",
  "very heavy rain": "very_heavy_rain",
  "extreme rain": "extreme_rain",
  "freezing rain": "freezing_rain",
  "light intensity shower rain": "light_intensity_shower_rain",
  "heavy intensity shower rain": "heavy_intensity_shower_rain",
  "light snow": "light_snow",
  "heavy snow": "heavy_snow",
  sleet: "sleet",
  "light shower sleet": "light_shower_sleet",
  "shower sleet": "shower_sleet",
  "light rain and snow": "light_rain_and_snow",
  "rain and snow": "rain_and_snow",
  "light shower snow": "light_shower_snow",
  "shower snow": "shower_snow",
  "heavy shower snow": "heavy_shower_snow",
  haze: "haze",
  smoke: "smoke",
  dust: "dust",
  sand: "sand",
  "volcanic ash": "volcanic_ash",
  squalls: "squalls",
  tornado: "tornado",
};

export const findDescriptionById = (id: string): string => {
  return idToKey[id] ?? "unknown";
};
