const idToKey: Record<string, string> = {
  "clear sky": "clear_sky",
  "few clouds": "few_clouds",
  "scattered clouds": "scattered_clouds",
  "broken clouds": "broken_clouds",
  "overcast clouds": "overcast_clouds",
  "shower rain": "shower_rain",
  rain: "rain",
  thunderstorm: "thunderstorm",
  snow: "snow",
  mist: "mist",
  fog: "fog",
  drizzle: "drizzle",
  "light rain": "light_rain",
  "moderate rain": "moderate_rain",
  "heavy intensity rain": "heavy_intensity_rain",
  "very heavy rain": "very_heavy_rain",
  "extreme rain": "extreme_rain",
  "freezing rain": "freezing_rain",
  "light intensity shower rain": "light_intensity_shower_rain",
  "heavy intensity shower rain": "heavy_intensity_shower_rain",
  "light snow": "light_snow",
  "heavy snow": "heavy_snow",
  sleet: "sleet",
  "light shower sleet": "light_shower_sleet",
  "shower sleet": "shower_sleet",
  "light rain and snow": "light_rain_and_snow",
  "rain and snow": "rain_and_snow",
  "light shower snow": "light_shower_snow",
  "shower snow": "shower_snow",
  "heavy shower snow": "heavy_shower_snow",
  haze: "haze",
  smoke: "smoke",
  dust: "dust",
  sand: "sand",
  "volcanic ash": "volcanic_ash",
  squalls: "squalls",
  tornado: "tornado",
};

export const findDescriptionById = (id: string): string => {
  return idToKey[id] ?? "unknown";
};
